name: py39dj_dk
channels:
#  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python 3.9
  - django 3.2.15
  - flake8 6.0.0
  - psycopg2 #2.8.6
  - pillow
  - uwsgi
  - pip
  - pip:
     - djangorestframework==3.14
     - drf-spectacular==0.27.1
#    - -r file:/tmp/requirements.txt
variables:
  DEV: false
